### PR TITLE
Read a promotion

### PR DESCRIPTION
**Pull request by reneesun**
### Testing

```
Name                  Stmts   Miss  Cover
-----------------------------------------
service/__init__.py      20      3    85%
service/models.py        40      2    95%
service/service.py       42      1    98%
-----------------------------------------
TOTAL                   102      6    94%
----------------------------------------------------------------------
```
### Pylint
service/model.py 10.00/10
service/service.py 0.00/10
service/__init__.py -4.74/10
tests/ 6.07/10

### CODE REVIEW

**Comment by reneesun** [comment]
Sure!

**Comment by KailiDing1121** [comment]
It seems like we have a merge conflict here. It should be conflicts from skeleton though.

**Comment by iamnwi** [comment]
The code looks good. Could you also update your PR comment to show the latest test running result?

**Comment by reneesun** [comment]
I've updated the latest test result.

**Comment by reneesun** [comment]
> It seems like we have a merge conflict here. It should be conflicts from skeleton though.

Resolved the conflict now.

**Pull request merged**
